services:
  - type: web
    name: Mywebsite-odoo
    env: docker
    plan: free
    autoDeploy: true

    startCommand: ""   # Lo dejamos vacío porque ya lo manejas en CMD del Dockerfile

    envVars:
      - key: ODOO_DB_HOST
        fromService:
          name: odoo-postgres
          type: pserv
      - key: ODOO_DB_PORT
        value: 5432
      - key: ODOO_DB_NAME
        value: odoo
      - key: ODOO_DB_USER
        value: odoo
      - key: ODOO_DB_PASSWORD
        generateValue: true
      - key: ODOO_ADMIN_PASSWD
        value: adminodoo

  - type: pserv
    name: odoo-postgres
    env: postgres
    plan: free
    envVars:
      - key: POSTGRES_DB
        value: odoo
      - key: POSTGRES_USER
        value: odoo
      - key: POSTGRES_PASSWORD
        generateValue: true
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
