services:
  - type: web
    name: odoo
    env: docker
    plan: free
    autoDeploy: true

    startCommand: >
      odoo --db_host=$ODOO_DB_HOST
           --db_port=$ODOO_DB_PORT
           --db_user=$ODOO_DB_USER
           --db_password=$ODOO_DB_PASSWORD
           --db_name=$ODOO_DB_NAME
           --admin_passwd=$ODOO_ADMIN_PASSWD
           --addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

    envVars:
      - key: ODOO_DB_HOST
        fromService:
          name: odoo-postgres
          type: pserv
      - key: ODOO_DB_PORT
        value: 5432
      - key: ODOO_DB_NAME
        value: odoo
      - key: ODOO_DB_USER
        value: odoo
      - key: ODOO_DB_PASSWORD
        generateValue: true
      - key: ODOO_ADMIN_PASSWD
        value: adminodoo

  - type: pserv
    name: odoo-postgres
    plan: free
    env: postgres
    envVars:
      - key: POSTGRES_DB
        value: odoo
      - key: POSTGRES_USER
        value: odoo
      - key: POSTGRES_PASSWORD
        generateValue: true
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
