services:
  - type: web
    name: odoo
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DB_HOST
        fromService:
          name: odoo-postgres
          type: pserv
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: odoo
      - key: DB_USER
        value: odoo
      - key: DB_PASSWORD
        generateValue: true
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8069

  - type: pserv
    name: odoo-postgres
    plan: free
    env: postgres
    envVars:
      - key: POSTGRES_DB
        value: odoo
      - key: POSTGRES_USER
        value: odoo
      - key: POSTGRES_PASSWORD
        generateValue: true
